all: inflation mortgage reverseArgs gonzo

inflation: inflation.cpp
	g++ -std=c++11 -o inflation inflation.cpp

mortgage: mortgage.cpp
	g++ -std=c++11 -o inflation inflation.cpp

reverseArgs: reverseArgs.cpp
	g++ -std=c++11 -o reverseArgs reverseArgs.cpp

gonzo: gonzo.cpp
	g++ -std=c++11 -o gonzo gonzo.cpp